require("dotenv").config();

const mongoose = require("mongoose");
const Product = require("../models/product.model");

const MONGO_URI = process.env.MONGO_URI;

const products = [
  {
    name: "Broiler Chicken",
    category: "Live Bird",
    unit: "KG",
    price: 220,
    stock: 1000,
    minimumStock: 30,
    description: "Healthy live broiler chicken",
    image: "https://res.cloudinary.com/zofwznzg/image/upload/v1784343593/Sweepstakesbible_Blog_e9zba3.jpg",
  },
  {
    name: "Layer Chicken",
    category: "Live Bird",
    unit: "KG",
    price: 280,
    stock: 500,
    minimumStock: 20,
    description: "Egg laying chicken",
    image: "https://res.cloudinary.com/zofwznzg/image/upload/v1784343587/A22-Layer-Performance-Factors-01-1200x630_bh65il.jpg",
  },
  {
    name: "Country Chicken",
    category: "Live Bird",
    unit: "KG",
    price: 450,
    stock: 500,
    minimumStock: 10,
    description: "Organic country chicken",
    image: "https://res.cloudinary.com/zofwznzg/image/upload/v1784343585/country-chicken-nati-chicken-whole-500x500_vkk9mv.webp",
  },
  {
    name: "Chicken Eggs",
    category: "Eggs",
    unit: "PIECE",
    price: 8,
    stock: 300000,
    minimumStock: 500,
    description: "Fresh poultry eggs",
    image: "https://res.cloudinary.com/zofwznzg/image/upload/v1784343591/poultry-egg-500x500_gsj2zb.webp",
  },
  {
    name: "Brown Eggs",
    category: "Eggs",
    unit: "PIECE",
    price: 10,
    stock: 20000,
    minimumStock: 300,
    description: "Premium brown eggs",
    image: "https://res.cloudinary.com/zofwznzg/image/upload/v1784343585/brow_ggs-free-range-chickens-local-poultry-farm-sustainable-agriculture-close-up-brown-carton-370932505_bhhvhy.webp",
  },
  {
    name: "Starter Feed",
    category: "Feed",
    unit: "KG",
    price: 45,
    stock: 6000,
    minimumStock: 100,
    description: "Starter feed for chicks",
    image: "https://res.cloudinary.com/zofwznzg/image/upload/v1784343586/images_chick_starter_qiusix.jpg",
  },
  {
    name: "Grower Feed",
    category: "Feed",
    unit: "KG",
    price: 42,
    stock: 8000,
    minimumStock: 150,
    description: "Grower feed",
    image: "https://res.cloudinary.com/zofwznzg/image/upload/v1784343593/24_-Poultry-Grower-in-background_2048x_vdycny.webp",
  },
  {
    name: "Finisher Feed",
    category: "Feed",
    unit: "KG",
    price: 44,
    stock: 700,
    minimumStock: 120,
    description: "Finisher feed",
    image: "https://res.cloudinary.com/zofwznzg/image/upload/v1784343591/poultry-feed-broiler-finisher_prreih.jpg",
  },
  {
    name: "Layer Feed",
    category: "Feed",
    unit: "KG",
    price: 46,
    stock: 650,
    minimumStock: 100,
    description: "Layer feed",
    image: "https://res.cloudinary.com/zofwznzg/image/upload/v1784343590/images_e1fmvr.jpg",
  },
  {
    name: "Maize",
    category: "Feed",
    unit: "KG",
    price: 30,
    stock: 900,
    minimumStock: 150,
    description: "Yellow maize",
    image: "https://res.cloudinary.com/zofwznzg/image/upload/v1784343592/yellow-maize-animal-feed-500x500_r5zn06.webp",
  },
  {
    name: "Soybean Meal",
    category: "Feed",
    unit: "KG",
    price: 52,
    stock: 400,
    minimumStock: 80,
    description: "Protein rich feed",
    image: "https://res.cloudinary.com/zofwznzg/image/upload/v1784343594/Optimizing-Soy-Protein-Practices-for-Higher-Nutrient-Efficiency-in-Poultry-Supply-Chains-1024x576_poh0pk.webp",
  },
  {
    name: "Rice Bran",
    category: "Feed",
    unit: "KG",
    price: 26,
    stock: 550,
    minimumStock: 80,
    description: "Rice bran",
    image: "https://res.cloudinary.com/zofwznzg/image/upload/v1784343593/poultry_rice_bran_QL80__lasas8.jpg",
  },
  {
    name: "Limestone Powder",
    category: "Feed Supplement",
    unit: "KG",
    price: 18,
    stock: 300,
    minimumStock: 50,
    description: "Calcium supplement",
    image: "https://res.cloudinary.com/zofwznzg/image/upload/v1784343590/powder_feed_vgaf8i.jpg",
  },
  {
    name: "Vitamin Premix",
    category: "Medicine",
    unit: "KG",
    price: 350,
    stock: 80,
    minimumStock: 15,
    description: "Vitamin supplement",
    image: "https://res.cloudinary.com/zofwznzg/image/upload/v1784343592/vitamin_premiximages_1_k8ie4n.jpg",
  },
  {
    name: "Mineral Mix",
    category: "Medicine",
    unit: "KG",
    price: 280,
    stock: 100,
    minimumStock: 20,
    description: "Mineral supplement",
    image: "https://source.unsplash.com/600x600/?minerals,supplement",
  },
  {
    name: "Newcastle Vaccine",
    category: "Medicine",
    unit: "PIECE",
    price: 220,
    stock: 50,
    minimumStock: 10,
    description: "ND Vaccine",
    image: "https://source.unsplash.com/600x600/?vaccine",
  },
  {
    name: "IBD Vaccine",
    category: "Medicine",
    unit: "PIECE",
    price: 180,
    stock: 45,
    minimumStock: 10,
    description: "Gumboro Vaccine",
    image: "https://source.unsplash.com/600x600/?medical,vaccine",
  },
  {
    name: "Antibiotic Powder",
    category: "Medicine",
    unit: "KG",
    price: 600,
    stock: 25,
    minimumStock: 5,
    description: "Broad spectrum antibiotic",
    image: "https://source.unsplash.com/600x600/?antibiotic,powder",
  },
  {
    name: "Electrolyte Powder",
    category: "Medicine",
    unit: "KG",
    price: 320,
    stock: 60,
    minimumStock: 10,
    description: "Electrolyte supplement",
    image: "https://source.unsplash.com/600x600/?electrolyte",
  },
  {
    name: "Disinfectant",
    category: "Medicine",
    unit: "KG",
    price: 240,
    stock: 70,
    minimumStock: 10,
    description: "Farm disinfectant",
    image: "https://source.unsplash.com/600x600/?disinfectant",
  },
  {
    name: "Plastic Feeder",
    category: "Equipment",
    unit: "PIECE",
    price: 280,
    stock: 120,
    minimumStock: 20,
    description: "Chicken feeder",
    image: "https://source.unsplash.com/600x600/?chicken,feeder",
  },
  {
    name: "Automatic Feeder",
    category: "Equipment",
    unit: "PIECE",
    price: 1400,
    stock: 25,
    minimumStock: 5,
    description: "Automatic feeder",
    image: "https://source.unsplash.com/600x600/?automatic,feeder",
  },
  {
    name: "Water Drinker",
    category: "Equipment",
    unit: "PIECE",
    price: 180,
    stock: 180,
    minimumStock: 30,
    description: "Water drinker",
    image: "https://res.cloudinary.com/zofwznzg/image/upload/v1784539567/a67af46654e32a9e43a2fc1bcc6b79e6_uqibza.jpg",
  },
  {
    name: "Brooder Lamp",
    category: "Equipment",
    unit: "PIECE",
    price: 650,
    stock: 40,
    minimumStock: 10,
    description: "Heating lamp",
    image: "https://res.cloudinary.com/zofwznzg/image/upload/v1784539299/089ed33c6d72756bfd858b7611886b6a_e9ehyb.jpg",
  },
  {
    name: "Egg Tray",
    category: "Equipment",
    unit: "PIECE",
    price: 35,
    stock: 500,
    minimumStock: 100,
    description: "30 egg tray",
    image: "https://source.unsplash.com/600x600/?egg,tray",
  },
  {
    name: "Chicken Cage",
    category: "Equipment",
    unit: "PIECE",
    price: 3500,
    stock: 20,
    minimumStock: 5,
    description: "Layer cage",
    image: "https://source.unsplash.com/600x600/?chicken,cage",
  },
  {
    name: "Wood Shavings",
    category: "Bedding",
    unit: "KG",
    price: 15,
    stock: 900,
    minimumStock: 150,
    description: "Bedding material",
    image: "https://source.unsplash.com/600x600/?wood,shavings",
  },
  {
    name: "Rice Husk",
    category: "Bedding",
    unit: "KG",
    price: 12,
    stock: 1000,
    minimumStock: 200,
    description: "Rice husk bedding",
    image: "https://res.cloudinary.com/zofwznzg/image/upload/v1784539463/8e7af0fe51aff7ec64cd1b37a061b496_jfen9x.jpg",
  },
  {
    name: "Charcoal Powder",
    category: "Supplement",
    unit: "KG",
    price: 65,
    stock: 150,
    minimumStock: 20,
    description: "Digestive supplement",
    image: "https://source.unsplash.com/600x600/?charcoal,powder",
  },
  {
    name: "Probiotic Mix",
    category: "Supplement",
    unit: "KG",
    price: 480,
    stock: 55,
    minimumStock: 10,
    description: "Gut health supplement",
    image: "https://source.unsplash.com/600x600/?probiotic",
  },
];

async function seedProducts() {
  try {
    await mongoose.connect(MONGO_URI);

    console.log("MongoDB Connected");

    await Product.deleteMany();

    await Product.insertMany(products);

    console.log(`✅ ${products.length} products inserted successfully`);

    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

seedProducts();